version: "3.8"

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.9.10-community
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    ports:
      - "10.1.0.229:9000:9000"
    environment:
#      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://10.1.0.229/sonarqube?currentSchema=sonar_schema
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=root
      - SONAR_JDBC_MAXACTIVE=60
      - SONAR_JDBC_MAXIDLE=5
      - SONAR_JDBC_MINIDLE=2
      - SONAR_JDBC_MAXWAIT=5000
#      - SONAR_JDBC_USERNAME=sonar
#      - SONAR_JDBC_PASSWORD=sonar
    networks:
      - sonarqube_network

networks:
  sonarqube_network:
    name: sonarqube_network
    driver: bridge

volumes:
  sonarqube-data:
    external: true
  sonarqube-logs:
    external: true
  sonarqube-extensions:
    external: true
