services:
  redis1:
    container_name: redis1
    image: redis:6.0.9-alpine
    restart: always
    hostname: "redis1.gmahechas.local"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - redis1_data:/data
      - ./ssl:/etc/ssl:ro
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "6380:6380" # ssl port
    entrypoint: ["/bin/sh", "/usr/local/bin/scripts/init.sh", "redis1.gmahechas.local", "redis1"]
    networks:
      redis_network:
        aliases:
          - redis1.gmahechas.local
        ipv4_address: 172.28.0.2

  redis2:
    container_name: redis2
    image: redis:6.0.9-alpine
    restart: always
    hostname: "redis2.gmahechas.local"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - redis2_data:/data
      - ./ssl:/etc/ssl:ro
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "6480:6380" # ssl port
    depends_on:
      - redis1
    entrypoint: ["/bin/sh", "/usr/local/bin/scripts/init.sh", "redis2.gmahechas.local", "redis2"]
    networks:
      redis_network:
        aliases:
          - redis2.gmahechas.local
        ipv4_address: 172.28.0.3

  redis3:
    container_name: redis3
    image: redis:6.0.9-alpine
    restart: always
    hostname: "redis3.gmahechas.local"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - redis3_data:/data
      - ./ssl:/etc/ssl:ro
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "6580:6380" # ssl port
    depends_on:
      - redis2
    entrypoint: ["/bin/sh", "/usr/local/bin/scripts/init.sh", "redis3.gmahechas.local", "redis3"]
    networks:
      redis_network:
        aliases:
          - redis3.gmahechas.local
        ipv4_address: 172.28.0.4

  redis_init:
    container_name: redis_init
    image: redis:6.0.9-alpine
    hostname: redis_init
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./scripts:/usr/local/bin/scripts:ro
    depends_on:
      - redis1
      - redis2
      - redis3
    entrypoint: ["/bin/sh", "/usr/local/bin/scripts/init-cluster.sh"]
    networks:
      - redis_network

volumes:
  redis1_data:
    driver: local
  redis2_data:
    driver: local
  redis3_data:
    driver: local

networks:
  redis_network:
    name: redis_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
