global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'null-receiver'

  routes:
    - match:
        severity: critical
      receiver: 'null-receiver'
    - match:
        severity: warning
      receiver: 'null-receiver'
    - match_re:
        service: ".*database.*"
      receiver: 'null-receiver'

receivers:
  - name: 'null-receiver'
