services:
  consul:
    container_name: consul
    image: hashicorp/consul-template:0.37
    volumes:
      - consul-secrets:/run/secrets
      - ./config:/etc/consul-template/config
    networks:
      - consul_network
      - vault_network
    command: >
      consul-template -config="/etc/consul-template/config/config.hcl" -template="/etc/consul-template/config/config.yml.tpl:/etc/consul-template/config/config.yml" -log-level=debug -once

volumes:
  consul-secrets:
    driver: local

networks:
  consul_network:
    name: consul_network
    driver: bridge
  vault_network:
    external: true

