services:
  redisdb1:
    container_name: redisdb1
    image: redis:6.0.9-alpine
    restart: always
    hostname: "redisdb1.gmahechas.local"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - redisdb1_data:/data
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "6379:6379"
    entrypoint: ["/bin/sh", "/usr/local/bin/scripts/init.sh", "redisdb1.gmahechas.local"]
    networks:
      redis_network:
        aliases:
          - redisdb1.gmahechas.local
        ipv4_address: 172.28.0.2

  redisdb2:
    container_name: redisdb2
    image: redis:6.0.9-alpine
    restart: always
    hostname: "redisdb2.gmahechas.local"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - redisdb2_data:/data
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "6479:6379"
    depends_on:
      - redisdb1
    entrypoint: ["/bin/sh", "/usr/local/bin/scripts/init.sh", "redisdb2.gmahechas.local"]
    networks:
      redis_network:
        aliases:
          - redisdb2.gmahechas.local
        ipv4_address: 172.28.0.3

  redisdb3:
    container_name: redisdb3
    image: redis:6.0.9-alpine
    restart: always
    hostname: "redisdb3.gmahechas.local"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - redisdb3_data:/data
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "6579:6379"
    depends_on:
      - redisdb2
    entrypoint: ["/bin/sh", "/usr/local/bin/scripts/init.sh", "redisdb3.gmahechas.local"]
    networks:
      redis_network:
        aliases:
          - redisdb3.gmahechas.local
        ipv4_address: 172.28.0.4

  redisdb_init:
    container_name: redisdb_init
    image: redis:6.0.9-alpine
    hostname: redisdb_init
    volumes:
      - ./scripts:/usr/local/bin/scripts:ro
    depends_on:
      - redisdb1
      - redisdb2
      - redisdb3
    entrypoint: ["/bin/sh", "/usr/local/bin/scripts/init-cluster.sh"]
    networks:
      - redis_network

volumes:
  redisdb1_data:
    driver: local
  redisdb2_data:
    driver: local
  redisdb3_data:
    driver: local

networks:
  redis_network:
    name: redis_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
