services:
  consul_template:
    container_name: consul_template
    image: hashicorp/consul-template:0.37
    environment:
      VAULT_ADDR: 'http://vault.gmahechas.local:8200'
      VAULT_ROLE_ID: 'tu_role_id'
      VAULT_SECRET_ID: 'tu_secret_id'
    volumes:
      - consul-template-data:/run/secrets
      - ./templates:/templates
      - ./config.hcl:/etc/consul-template/config.hcl
    networks:
      - consul_template_network
    command: >
      consul-template -config="/etc/consul-template/config.hcl" -log-level=debug -once

volumes:
  consul-template-data:
    external: true  

networks:
  consul_template_network:
    name: consul_template_network
    driver: bridge

