services:
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine3.19-bleeding
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/etc/gitlab-runner/config.toml
    networks:
      - gitlab_ce_network

networks:
  gitlab_ce_network:
    name: gitlab_ce_network
    driver: bridge

#docker exec -it gitlab-runner /bin/bash