services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.52.0
    restart: always
    hostname: "prometheus"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - prometheus_data:/prometheus
      - ./ssl:/etc/ssl:ro
      - ./prometheus-config:/etc/config
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/config/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.listen-address=:9090"
      - "--web.external-url=prometheus-shared3.gmahechas.local"
      - "--web.config.file=/etc/config/web-config.yml"
    dns:
      - 10.1.0.1
    networks:
      - prometheus_network

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.27.0
    restart: always
    hostname: "alertmanager"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - ./alertmanager-config:/etc/config
    ports:
      - "9093:9093"
    depends_on:
      - prometheus
    dns:
      - 10.1.0.1
    command:
      - "--config.file=/etc/config/alertmanager.yml"
      - "--web.listen-address=:9093"
    networks:
      - prometheus_network

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:10.4.4
    restart: unless-stopped
    hostname: "grafana"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=root
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    dns:
      - 10.1.0.1
    networks:
      - prometheus_network

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  prometheus_network:
    name: prometheus_network
    driver: bridge