services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:16.10.3-ce.0
    restart: always
    hostname: 'gitlab'
    cpus: 2.0
    mem_limit: 4g
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://gitlab:8928'
        gitlab_rails['gitlab_shell_ssh_port'] = 2423
    ports:
      - '8928:8928'
      - '2423:2423'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
    shm_size: '256m'
    networks:
      - gitlab_network
    
networks:
  gitlab_network:
    name: gitlab_network
    driver: bridge

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:

# docker exec gitlab grep 'Password:' /etc/gitlab/initial_root_password
# https://docs.gitlab.com/ee/install/docker.html#pre-configure-docker-container