version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.17-focal
    volumes:
      - mongodb-dbs:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - mongodb_network

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge

volumes:
  mongodb-dbs:
    external: true
