services:
  mongodb1:
    container_name: mongodb1
    image: mongo:4.2.10
    restart: always
    hostname: 'mongodb1.gmahechas.local'
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - mongodb1_data:/data/db
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "27017:27017"
    entrypoint: ["/bin/bash", "/usr/local/bin/scripts/init.sh"]
    networks:
      mongodb_network:
        aliases:
          - mongodb1.gmahechas.local

  mongodb2:
    container_name: mongodb2
    image: mongo:4.2.10
    restart: always
    hostname: 'mongodb2.gmahechas.local'
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - mongodb2_data:/data/db
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "28017:27017"
    entrypoint: ["/bin/bash", "/usr/local/bin/scripts/init.sh"]
    networks:
      mongodb_network:
        aliases:
          - mongodb2.gmahechas.local

  mongodb3:
    container_name: mongodb3
    image: mongo:4.2.10
    restart: always
    hostname: 'mongodb3.gmahechas.local'
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - mongodb3_data:/data/db
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "29017:27017"
    entrypoint: ["/bin/bash", "/usr/local/bin/scripts/init.sh"]
    networks:
      mongodb_network:
        aliases:
          - mongodb3.gmahechas.local

  mongodb_init:
    container_name: mongodb_init
    image: mongo:4.2.10
    hostname: 'mongodb_init'
    volumes:
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    entrypoint: ["/bin/bash", "/usr/local/bin/scripts/init-rs.sh"]
    networks:
      - mongodb_network

volumes:
  mongodb1_data:
    driver: local
  mongodb2_data:
    driver: local
  mongodb3_data:
    driver: local

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge
