services:
  mongodb1:
    container_name: mongodb1
    image: mongo:4.2.10
    restart: always
    hostname: "mongodb1.gmahechas.local"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - mongodb1_data:/data/db
      - ./ssl:/etc/ssl:ro
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "27017:27017"
    entrypoint: ["/bin/bash", "/usr/local/bin/scripts/init.sh", "27017"]
    networks:
      - mongodb_network

  mongodb2:
    container_name: mongodb2
    image: mongo:4.2.10
    restart: always
    hostname: "mongodb2.gmahechas.local"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - mongodb2_data:/data/db
      - ./ssl:/etc/ssl:ro
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "28017:28017"
    depends_on:
      - mongodb1
    entrypoint: ["/bin/bash", "/usr/local/bin/scripts/init.sh", "28017"]
    networks:
      - mongodb_network

  mongodb3:
    container_name: mongodb3
    image: mongo:4.2.10
    restart: always
    hostname: "mongodb3.gmahechas.local"
    cpus: 1.0
    mem_limit: 1g
    volumes:
      - mongodb3_data:/data/db
      - ./ssl:/etc/ssl:ro
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    ports:
      - "29017:29017"
    depends_on:
      - mongodb2
    entrypoint: ["/bin/bash", "/usr/local/bin/scripts/init.sh", "29017"]
    networks:
      - mongodb_network

  mongodb_init:
    container_name: mongodb_init
    image: mongo:4.2.10
    hostname: "mongodb_init"
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./config:/etc/config
      - ./scripts:/usr/local/bin/scripts:ro
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    entrypoint: ["/bin/bash", "/usr/local/bin/scripts/init-rs.sh"]
    networks:
      - mongodb_network

  mongodb_exporter:
    container_name: mongodb_exporter
    image: percona/mongodb_exporter:0.40.0
    hostname: "mongodb_exporter"
    volumes:
      - ./ssl:/etc/ssl:ro
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
      - mongodb_init
    command:
      - "--mongodb.user=root"
      - "--mongodb.password=root"
      - "--mongodb.uri=mongodb://mongodb1.gmahechas.local:27017/?tls=true&tlsCertificateKeyFile=/etc/ssl/client/client.pem&tlsCAFile=/etc/ssl/ca.crt&authSource=admin,mongodb://mongodb2.gmahechas.local:28017/?tls=true&tlsCertificateKeyFile=/etc/ssl/client/client.pem&tlsCAFile=/etc/ssl/ca.crt&authSource=admin,mongodb://mongodb3.gmahechas.local:29017/?tls=true&tlsCertificateKeyFile=/etc/ssl/client/client.pem&tlsCAFile=/etc/ssl/ca.crt&authSource=admin"
      - "--collect-all"
      - "--log.level=debug"
    networks:
      - mongodb_network

volumes:
  mongodb1_data:
    driver: local
  mongodb2_data:
    driver: local
  mongodb3_data:
    driver: local

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge
