services:
  nginx:
    container_name: nginx
    image: nginx:1.27.0-alpine
    restart: always
    hostname: 'nginx'
    cpus: 1.0
    mem_limit: 1g
    ports:
      - '443:443'
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_network
      - mongodb_network
      - redis_network
    
networks:
  nginx_network:
    name: nginx_network
    driver: bridge
  mongodb_network:
    external: true
  redis_network:
    external: true