version: "3.8"

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.385-alpine
    ports:
      - "10.1.0.229:8080:8080"
      - "10.1.0.229:50000:50000"
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - jenkins_network

networks:
  jenkins_network:
    name: jenkins_network
    driver: bridge

volumes:
  jenkins:
    external: true
