version: "3.8"

services:
  vault:
    container_name: vault
    image: vault:1.6.1
    ports:
      - "10.1.0.229:8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=myroot
    volumes: 
      - ./policy:/vault/policy
    networks:
      - vault_network

networks:
  vault_network:
    name: vault_network
    driver: bridge

#docker exec vault sh vault/policy/jaya/PoliciesAndAppRole.txt
