services:
  vault:
    container_name: vault
    image: vault:1.13.3
    restart: unless-stopped
    hostname: 'vault'
    cpus: 1.0
    mem_limit: 1g
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://vault.gmahechas.local:8200
    ports:
      - "8200:8200"
    volumes: 
      - ./config:/vault/config
      - vault-logs:/vault/logs
      - vault-data:/vault/data
    networks:
      - vault_network
    user: 'vault:vault' # fix permissions
    cap_add:
      - IPC_LOCK
    command:
      - "server"

volumes:
  vault-logs:
    driver: local
  vault-data:
    driver: local

networks:
  vault_network:
    name: vault_network
    driver: bridge
