version: "3.8"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5.5
    volumes:
      - mariadb-dbs:/var/lib/mysql
      - ./backup:/backup
    ports:
      - "10.1.0.229:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mariadb_network

#  phpmyadmin:
#    container_name: phpmyadmin
#    image: phpmyadmin:5.0.2
#    ports:
#      - "10.1.0.229:81:80"
#    environment:
#      - PMA_HOST=mariadb
#    networks:
#      - mariadb_network
#    depends_on:
#      - mariadb

networks:
  mariadb_network:
    name: mariadb_network
    driver: bridge

volumes:
  mariadb-dbs:
    external: true
