apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "v0.0.1"
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.10
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: root
        ports:
          - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      nodePort: 30019
      port: 27018
      targetPort: 27017
  