services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:16.10.3-ce.0
    restart: always
    hostname: 'gitlab.gmahechas.net'
    cpus: 2.0
    mem_limit: 4g
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.gmahechas.net:8929'
        nginx['listen_port'] = 8929
        nginx['listen_https'] = true
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.gmahechas.net.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.gmahechas.net.key"
        nginx['custom_gitlab_server_config'] = "listen 80;"
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '80:80'
      - '2424:2424'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - './certificate:/etc/gitlab/ssl'
    shm_size: '256m'
    networks:
      - gitlab_network
    
networks:
  gitlab_network:
    name: gitlab_network
    driver: bridge

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:

# docker exec gitlab grep 'Password:' /etc/gitlab/initial_root_password
# https://docs.gitlab.com/ee/install/docker.html#pre-configure-docker-container