version: "3.8"

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.0 
    ports:
      - "10.1.0.229:2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafka_network

  kafka0:
    container_name: kafka0
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - "10.1.0.229:9090:9090"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.1.0.229:9090
      - KAFKA_BROKER_ID=0
    networks:
      - kafka_network
    depends_on:
      - zookeeper

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - "10.1.0.229:9091:9091"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.1.0.229:9091
      - KAFKA_BROKER_ID=1
    networks:
      - kafka_network
    depends_on:
     - kafka0

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:7.0.0
    ports:
      - "10.1.0.229:9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.1.0.229:9092
      - KAFKA_BROKER_ID=2
    networks:
      - kafka_network
    depends_on:
      - kafka1

networks:
  kafka_network:
    name: kafka_network
    driver: bridge
