version: "3.8"

services:
  vault:
    container_name: vault9
    image: vault:1.9.2
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
#      - VAULT_DEV_ROOT_TOKEN_ID=myroot
#      - VAULT_DEV_LISTEN_ADDRESS=http://127.0.0.1:8200
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    volumes: 
      - ./config:/vault/config
    networks:
      - vault_network
    command:
      - "server"
networks:
  vault_network:
    name: vault_network
    driver: bridge
