version: "3.8"

services:
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:1.12.1
    ports:
      - "8001:8001"
    networks:
      - redisinsight_network

networks:
  redisinsight_network:
    name: redisinsight_network
    driver: bridge
