services:
  postgres:
    container_name: postgres
    image: postgres:14.11-alpine3.19
    restart: unless-stopped
    hostname: 'postgres'
    cpus: 1.0
    mem_limit: 1g
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql.custom.conf:/var/lib/postgresql/postgresql.custom.conf
      - ./pg_hba.custom.conf:/var/lib/postgresql/pg_hba.custom.conf
      - ./ssl:/var/lib/postgresql/ssl
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local  

networks:
  postgres-network:
    name: postgres-network
    driver: bridge

# chown postgres:postgres /var/lib/postgresql/data/ssl/server.key
# chmod 600 /var/lib/postgresql/data/ssl/server.key
# echo "include = '/var/lib/postgresql/data/postgresql.custom.conf'" >> /var/lib/postgresql/data/pgdata/postgresql.conf
# echo "include = '/var/lib/postgresql/data/pg_hba.custom.conf'" >> /var/lib/postgresql/data/pgdata/pg_hba.conf
# docker compose restart