services:
  postgres:
    container_name: postgres
    image: postgres:14.11-alpine3.19
    restart: unless-stopped
    hostname: 'postgres'
    cpus: 1.0
    mem_limit: 1g
    environment:
      - POSTGRES_PASSWORD=postgres # user: postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local

networks:
  postgres_network:
    name: postgres_network
    driver: bridge

