version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    volumes:
      - postgres-dbs:/var/lib/postgresql/data
    ports:
      - "10.1.0.229:5432:5432"
    environment:
#      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - postgres_network

networks:
  postgres_network:
    name: postgres_network
    driver: bridge

volumes:
  postgres-dbs:
    external: true
