services:
  postgres:
    container_name: postgres
    image: postgres:14.11-alpine3.19
    restart: unless-stopped
    hostname: 'postgres'
    cpus: 1.0
    mem_limit: 1g
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql.custom.conf:/var/lib/postgresql/data/pgdata/postgresql.custom.conf
      - ./pg_hba.custom.conf:/var/lib/postgresql/data/pgdata/pg_hba.custom.conf
      - ./ssl:/var/lib/postgresql/data/pgdata/ssl
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      /bin/sh -c "
      echo 'include = 'postgresql.custom.conf'' >> /var/lib/postgresql/data/pgdata/postgresql.conf &&
      echo 'include = ''pg_hba.custom.conf''' >> /var/lib/postgresql/data/pgdata/pg_hba.conf &&
      exec docker-entrypoint.sh postgres
      "

volumes:
  postgres-data:
    driver: local  

networks:
  postgres_network:
    name: postgres_network
    driver: bridge

